### ISSUE TITLE
Add Maglev Support 

### ISSUE THREAD

**Issue by copiousfreetime** [copiousfreetime/hitimes#16]
Implement the binary portion that is necessary to support maglev.

`System class>>nsTime` appears to be what is necessary.

I'll leave it to @jc00ke to start on for the moment. I won't be able to get to this until mid-late march at the earliest.

**Comment by copiousfreetime** [comment]
I'm guessing this isn't going to happen, so closing

**Comment by jc00ke** [comment]
@AllenOtis ?
