### ISSUE TITLE
Ruby 2.0.0 and Native Extensions

### ISSUE THREAD

**Issue by r38y** [copiousfreetime/hitimes#17]
I'm working on trying my Rails app with Ruby 2.0.0 and some of my gems use hitimes (1.1 and 1.2 have the same issue). I am getting the following error:

```
cannot load such file -- hitimes/hitimes
```

Which I think is because it can't find the version-specific extensions. I noticed that a file (?) gets created instead of a folder for 2.0:

![hitimes-ruby2 0](https://f.cloud.github.com/assets/926/189938/01eb2a60-7ebc-11e2-9b04-764c8f742f9b.png)

I think it may have to do with this line:

https://github.com/copiousfreetime/hitimes/blob/master/tasks/extension.rake#L38

I'm happy to work on a pull request but wanted to know if I am going in the right direction. I'm not really familiar with how native extensions work.

**Comment by stuarthannig** [comment]
Could serve Jekyll because of hitimes error, `gem install --verbose hitimes` did indeed fix problem.

**Comment by brewster1134** [comment]
updating from ruby 2.0.0-p0 fixed it for me.  seems any patch version other that p0 worked fine.

**Comment by stuarthannig** [comment]
Hm, my environment is running ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13] so I'm not sure why that wasn't the case for me.

**Comment by andrelugomes** [comment]
I have this problem with Ruby 2.2.0 trying to run Jekyll serve:

$ jekyll serve
c:/Ruby22/lib/ruby/gems/2.2.0/gems/liquid-2.6.1/lib/liquid/htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"
Configuration file: c:/Users/ricardo/workspace/jhipster.github.io/_config.yml
            Source: c:/Users/ricardo/workspace/jhipster.github.io
       Destination: c:/Users/ricardo/workspace/jhipster.github.io/_site
      Generating...
                    done.
c:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require': cannot load such file -- hitimes/hitimes (LoadError)
        from c:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/hitimes-1.2.2-x86-mingw32/lib/hitimes.rb:37:in `rescue in <top (required)>'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/hitimes-1.2.2-x86-mingw32/lib/hitimes.rb:32:in `<top (required)>'
        from c:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from c:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from c:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/timers-4.0.1/lib/timers/group.rb:4:in `<top (required)>'
        from c:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from c:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/timers-4.0.1/lib/timers.rb:4:in `<top (required)>'
        from c:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from c:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/receivers.rb:3:in `<top (required)>'
        from c:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from c:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid.rb:475:in `<top (required)>'
        from c:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from c:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/listen-2.10.0/lib/listen.rb:1:in `<top (required)>'
        from c:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from c:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/jekyll-watch-1.2.1/lib/jekyll/watcher.rb:26:in `build_listener'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/jekyll-watch-1.2.1/lib/jekyll/watcher.rb:7:in `watch'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:67:in `watch'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:37:in `process'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll/commands/serve.rb:25:in `block (2 levels) in init_with_program'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/bin/jekyll:18:in `<top (required)>'
        from c:/Ruby22/bin/jekyll:23:in `load'
        from c:/Ruby22/bin/jekyll:23:in `<main>'

**Comment by andrelugomes** [comment]
I found a solution... http://stackoverflow.com/questions/28985481/hitimes-require-error-when-running-jekyll-serve-on-windows-8-1

gem uni hitimes

**Remove ALL versions**

gem ins hitimes -v 1.2.1 --platform ruby

That will recompile hitimes that is compatible with Ruby 2.2.

**Comment by LukeMcGurdy** [comment]
I documented the same issue/ fix here for Win7 - http://lukemcgurdy.github.io/jekyll-hitimes-windows-7/

Same process as andrelugomes outlines.

**Comment by copiousfreetime** [comment]
@LukeMcGurdy I will get a new fatbinary version of hitimes out next week. See #40

**Comment by andrelugomes** [comment]
@copiousfreetime thanks
