### ISSUE TITLE
Update to use ruby 2.1's access to the clock monotonic

### ISSUE THREAD

**Issue by copiousfreetime** [copiousfreetime/hitimes#22]

**Comment by copiousfreetime** [comment]
This may also require a conditional in the extconf to see if the clock monotonic access in ruby is available, if so then it should not have to run the extension

**Comment by ioquatix** [comment]
Is the monotonic clock the same as what Hitimes currently uses?

**Comment by copiousfreetime** [comment]
@ioquatix I think under the covers it might. I need to do some testing on windows to see what ruby on windows does, or if it is even available.

**Comment by copiousfreetime** [comment]
Looks like under the covers ruby attempts to do the same thing I do, but out of the box it doesn't have the same resolution as I can get in hitimes. Ruby uses the same low level calls hitimes does, but uses the data a bit differently. For instance on OSX ruby only gives millisecond resolution while hitimes can give nanosecond - even though under the covers they both use `mach_absolute_time`
