### ISSUE TITLE
Can't bundle install hitimes with ruby ruby 2.1.2p95

### ISSUE THREAD

**Issue by holycow001** [copiousfreetime/hitimes#29]
here's the error i'm getting:
Installing hitimes (1.2.2) with native extensions
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /opt/chef/embedded/bin/ruby extconf.rb
creating Makefile

make
compiling hitimes.c
clang: warning: argument unused during compilation: '-L/opt/chef/embedded/lib'
compiling hitimes_instant_clock_gettime.c
clang: warning: argument unused during compilation: '-L/opt/chef/embedded/lib'
compiling hitimes_instant_osx.c
clang: warning: argument unused during compilation: '-L/opt/chef/embedded/lib'
compiling hitimes_instant_windows.c
clang: warning: argument unused during compilation: '-L/opt/chef/embedded/lib'
compiling hitimes_interval.c
clang: warning: argument unused during compilation: '-L/opt/chef/embedded/lib'
compiling hitimes_stats.c
clang: warning: argument unused during compilation: '-L/opt/chef/embedded/lib'
linking shared-object hitimes/1.9/hitimes.bundle
clang: error: unknown argument: '-R/opt/chef/embedded/lib'
make: *** [hitimes.bundle] Error 1

Gem files will remain installed in /Users/frank.kang/.bundler/tmp/14487/gems/hitimes-1.2.2 for inspection.
Results logged to /Users/frank.kang/.bundler/tmp/14487/gems/hitimes-1.2.2/ext/hitimes/c/gem_make.out
An error occured while installing hitimes (1.2.2), and Bundler cannot continue.
Make sure that `gem install hitimes -v '1.2.2'` succeeds before bundling.

installing with gem install hitimes -v 1.2.2 succeeds.

**Comment by copiousfreetime** [comment]
@holycow001 Since I haven't heard any response back from you, I'm going to assume that you have found a solution. If you would like to post them here I would appreciate it. In the meantime I'm closing this ticket.
