### ISSUE TITLE
Publish windows vesion of hightimes again

### ISSUE THREAD

**Issue by copiousfreetime** [copiousfreetime/hitimes#30]
From Issue #27 

>Hi,
>I am running ruby-rails on windows, i am not able to install hitimes. Getting following error:
>ERROR: Error installing hitimes:
>The 'hitimes' native gem requires installed build tools.

**Comment by copiousfreetime** [comment]
Well, its taken me about solid days of work to get the cross compilation environment up to get the versions out. 

I have pushed a cross-compiled ruby gem for [hitimes v1.2.2](https://rubygems.org/gems/hitimes/versions/1.2.2-x86-mswin32-60). It *should* work with windows ruby 1.9.3, 2.0.0 and 2.1.5. As I don't  have a windows machine to test this one, I haven't been able to say that it works. If you could all test it out I would appreciate it @Thijsrausch, @eregon.

If it works, then let me know and i'll close this out.

You can also use the [RubyInstaller DevKit](https://github.com/oneclick/rubyinstaller/wiki/Development-Kit) then it also appears to install from the source gem just fine.

**Comment by eregon** [comment]
Thanks!

Installation on a Ruby 2.1.5 (32-bit) by Ruby installer tells it needs the build tools. Maybe because the reported RUBY_PLATFORM is mingw32? Or the OS is 64-bit?
I will try later with the DevKit to see if that works.

**Comment by Thijsrausch** [comment]
It worked for me with the Devkit, thanks!

**Comment by eregon** [comment]
Here is my (old) Windows configuration:
```
C:\Users\eregon>ruby -S gem install hitimes
Fetching: hitimes-1.2.2.gem (100%)
ERROR:  Error installing hitimes:
        The 'hitimes' native gem requires installed build tools.

Please update your PATH to include build tools or download the DevKit
from 'http://rubyinstaller.org/downloads' and follow the instructions
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'

C:\Users\eregon>gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.0.3
  - RUBY VERSION: 2.0.0 (2013-06-27 patchlevel 247) [i386-mingw32]
  - INSTALLATION DIRECTORY: C:/Ruby200/lib/ruby/gems/2.0.0
  - RUBY EXECUTABLE: C:/Ruby200/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/Ruby200/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-mingw32
  - GEM PATHS:
     - C:/Ruby200/lib/ruby/gems/2.0.0
     - C:/Users/eregon/.gem/ruby/2.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/

C:\Users\eregon>ruby -e 'p Gem::Platform.local'
#<Gem::Platform:0xee8b58 @cpu="x86", @os="mingw32", @version=nil>

C:\Users\eregon>gem search -rd hitimes

*** REMOTE GEMS ***

hitimes (1.2.2, 1.2.1, 1.1.1)
    Platforms:
        1.1.1: x86-mingw32
        1.2.1: x86-mswin32
        1.2.2: java, ruby, x86-mswin32-60
    Author: Jeremy Hinegardner
    Homepage: http://github.com/copiousfreetime/hitimes

    Hitimes is a fast, high resolution timer library for recording
    performance metrics.  It uses the appropriate low method calls for
    each system to get the highest granularity time increments possible.
```
We can see the platform string seems indeed to be the problem.
We can force the platform with `--platform=x86-mswin32-60`:
```

C:\Users\eregon>ruby -S gem install hitimes --platform=x86-mswin32-60
Fetching: hitimes-1.2.2-x86-mswin32-60.gem (100%)
Successfully installed hitimes-1.2.2-x86-mswin32-60
Parsing documentation for hitimes-1.2.2-x86-mswin32-60
unable to convert "\x90" from ASCII-8BIT to UTF-8 for lib/hitimes/1.9/hitimes.so
, skipping
unable to convert "\x90" from ASCII-8BIT to UTF-8 for lib/hitimes/2.0/hitimes.so
, skipping
unable to convert "\x90" from ASCII-8BIT to UTF-8 for lib/hitimes/2.1/hitimes.so
, skipping
Installing ri documentation for hitimes-1.2.2-x86-mswin32-60
1 gem installed
```
hitimes.so should probably not be in the gem but it does not matter so much.

It looks like it works with `Hitimes::Interval.measure` and the tests:
`130 tests, 211 assertions, 0 failures, 0 errors, 0 skips`

So everything looks alright, just the platform should be set to `x86-mingw32` for seemless installation.
Thanks for the good work!

**Comment by copiousfreetime** [comment]
alright, looks like I'll need to package it multiple times. And yes, hitimes.so should be in there, that is what you are loading. That's the binary portion. I think I need to update the documentation regex so that it doesn't attempt to parse the .so files :-).

**Comment by eregon** [comment]
OK, I thought it would be a `.dll` but that looks to be a non-issue.

**Comment by copiousfreetime** [comment]
@krawatcoder @Thijsrausch @eregon [hitimes-1.2.2-x86-mingw32.gem](https://rubygems.org/gems/hitimes/versions/1.2.2-x86-mingw32) pushed to rubygems. If you are using the http://rubyinstaller.org/ then it should install just fine.

I'm going to close this now, since I think that should satisfy everyone. If that is not the case, please comment here.

**Comment by imarco** [comment]
I was trying to install octopress on windows8.1 which needs the hitimes just a few hours ago, and I was stucked. While I'm searching for the solution by google I was directed here and see the owner is working on it. I told mysel: "Oh what a sad message~".   
But just a few minutes passed, the problem was fixed by the owner unexpectedly. It's just fantastic! Thanks for your great work!

**Comment by copiousfreetime** [comment]
@imarco glad to help :smile: Please let me know if/when you have problems or bugs with hitimes
