### ISSUE TITLE
installing hitimes 1.2.2 fails in ruby-2.0.0-p598 [ x86_64 ] 

### ISSUE THREAD

**Issue by alladi** [copiousfreetime/hitimes#31]
Hi,

I am trying to install hittimes on osx 10.6.8 with ruby-2.0.0-p598 [ x86_64 ] and the gem install hitimes fails with the following error

Building native extensions.  This could take a while...
ERROR:  Error installing hitimes:
	ERROR: Failed to build gem native extension.

    /usr/local/rvm/rubies/ruby-2.0.0-p598/bin/ruby -r ./siteconf20141210-67072-de33kt.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling hitimes.c
compiling hitimes_instant_clock_gettime.c
compiling hitimes_instant_osx.c
compiling hitimes_instant_windows.c
compiling hitimes_interval.c
compiling hitimes_stats.c
linking shared-object hitimes/2.0/hitimes.bundle
ld: framework not found CoreServices
collect2: ld returned 1 exit status
make: *** [hitimes.bundle] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.0.0-p598/gems/hitimes-1.2.2 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.0.0-p598/extensions/x86_64-darwin-10/2.0.0/hitimes-1.2.2/gem_make.out

Where as if use the ruby-2.1.1 [ x86_64 ] version am able to install the gem. But my project runs on the earlier version of ruby. Please let me know how to fix this.

**Comment by copiousfreetime** [comment]
@alladi I did a bit of investigation, CoreServices is available in SnowLeopard (OS X 10.6.8) so I'm not sure why this is failing. It may be an issue with RVM and its setting of the load path, could you paste the content of  `./siteconf20141210-67072-de33kt.rb`. Or maybe update rvm, do a fresh install of ruby-2.0.0-p598 and see if that works?

**Comment by alladi** [comment]
Hi It was a version incompatibility. I have moved past that obstacle but don't remember exactly what I did but it was for sure to do with the gem versions dependency and due to which i had tried to install that particular gem but later I guess with changing the newer version of gems in my application that dependency was solved.

Cheers for the effort and thank you once again

**Comment by copiousfreetime** [comment]
Thanks @alladi I'll close this now.
