### ISSUE TITLE
Error installing hitimes on OS X Yosemite

### ISSUE THREAD

**Issue by brunzino** [copiousfreetime/hitimes#35]
I'm trying to install onto Yosemite using Bundler to no avail. I tried updating Bundler and installing gem individually from different directories. Error messages below.

```
$ gem install hitimes -v '1.2.2'
Building native extensions.  This could take a while...
ERROR:  Error installing hitimes:
	ERROR: Failed to build gem native extension.

    /Users/nbruns/.rvm/rubies/ruby-2.0.0-p247/bin/ruby extconf.rb
creating Makefile

make "DESTDIR="
compiling hitimes.c
compiling hitimes_instant_clock_gettime.c
compiling hitimes_instant_osx.c
compiling hitimes_instant_windows.c
compiling hitimes_interval.c
compiling hitimes_stats.c
linking shared-object hitimes/2.0/hitimes.bundle
ld: warning: directory not found for option '-L/Users/mpapis/.sm/pkg/active/lib'
ld: framework not found CoreServices
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [hitimes.bundle] Error 1


Gem files will remain installed in /Users/nbruns/.rvm/gems/ruby-2.0.0-p247/gems/hitimes-1.2.2 for inspection.
Results logged to /Users/nbruns/.rvm/gems/ruby-2.0.0-p247/gems/hitimes-1.2.2/ext/hitimes/c/gem_make.out
```

**Comment by copiousfreetime** [comment]
@brunzino Can you post the contents of `/Users/nbruns/.rvm/gems/ruby-2.0.0-p247/gems/hitimes-1.2.2/ext/hitimes/c/gem_make.out` somewhere?

**Comment by brunzino** [comment]
Odd: the gem_make.out file wasn't at the location described above. Since posting, however, I've updated RVM and rubygems, which could be the cause. Running the `gem install hitimes` again gives similar error message. The contents of the `gem_make.out` file are: 
```
$ cat /Users/nbruns/.rvm/gems/ruby-2.0.0-p247/extensions/x86_64-darwin-12/2.0.0-static/hitimes-1.2.2/gem_make.out
/Users/nbruns/.rvm/rubies/ruby-2.0.0-p247/bin/ruby -r ./siteconf20150128-12582-1dvwxvt.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling hitimes.c
compiling hitimes_instant_clock_gettime.c
compiling hitimes_instant_osx.c
compiling hitimes_instant_windows.c
compiling hitimes_interval.c
compiling hitimes_stats.c
linking shared-object hitimes/2.0/hitimes.bundle
ld: warning: directory not found for option '-L/Users/mpapis/.sm/pkg/active/lib'
ld: framework not found CoreServices
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [hitimes.bundle] Error 1

make failed, exit code 2
```

and for what it's worth, the output from running `gem install hitimes` on updated RVM, rubygems, bundler etc are: 
```
$ gem install hitimes
Building native extensions.  This could take a while...
ERROR:  Error installing hitimes:
	ERROR: Failed to build gem native extension.

    /Users/nbruns/.rvm/rubies/ruby-2.0.0-p247/bin/ruby -r ./siteconf20150128-12718-y78cvf.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling hitimes.c
compiling hitimes_instant_clock_gettime.c
compiling hitimes_instant_osx.c
compiling hitimes_instant_windows.c
compiling hitimes_interval.c
compiling hitimes_stats.c
linking shared-object hitimes/2.0/hitimes.bundle
ld: warning: directory not found for option '-L/Users/mpapis/.sm/pkg/active/lib'
ld: framework not found CoreServices
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [hitimes.bundle] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/nbruns/.rvm/gems/ruby-2.0.0-p247/gems/hitimes-1.2.2 for inspection.
Results logged to /Users/nbruns/.rvm/gems/ruby-2.0.0-p247/extensions/x86_64-darwin-12/2.0.0-static/hitimes-1.2.2/gem_make.out
```

Thanks, @copiousfreetime!

**Comment by copiousfreetime** [comment]
so far it seems that all the problems people are having on yosemite are with ruby-2.0.0. only, and only with those folks that are using rvm/sm. So, I think there must be a sm/rvm environment leakage or something like that.

**Comment by brunzino** [comment]
Thanks I'll play with those variables, will update.

**Comment by lfender6445** [comment]
@brunzino - you figure this out yet, I am hitting same issue

**Comment by paulomcnally** [comment]
Open Xcode and accept.

**Comment by copiousfreetime** [comment]
@brunzino can you check and make sure that `/Users/mpapis/.sm/pkg/active/lib` is a directory that exists? Since that's the first error, that could be what is triggering it. Also try @paulomcnally's suggestion of opening xcode up and seeing if it needs to do some configuration on open.

**Comment by brunzino** [comment]
Upgrading ruby to 2.1[.5] worked. 
```
rvm install 2.1
```
Now it's just a matter of getting other gems to install on ruby 2.1 :/

`/Users/mpapis/.sm/pkg/active/lib` does not exist on my machine; that looks like a reference to a local directory on Michal Papis' machine (creator of RVM), which is interesting.

**Comment by copiousfreetime** [comment]
Alright, I'm going to close this. For posterity, I think I'm going to say that for Yosemite support it is possible you need to be on Ruby 2.1 or greater.

**Comment by andyatkinson** [comment]
After upgrading to Yosemite, I ran into this, but was able to fix it by updating Xcode (with restart).

**Comment by copiousfreetime** [comment]
For posterity, Please see https://github.com/rvm/rvm/issues/3360 for the solution.
