### ISSUE TITLE
Trouble installing hitimes when space in path

### ISSUE THREAD

**Issue by amyrlam** [copiousfreetime/hitimes#37]
I have an error similar to https://github.com/copiousfreetime/hitimes/issues/35, but I think the error is because my path has a space in it. 

My path to my virtual environment: 
```/Volumes/alam's home/fastly/fastly-jekyll/_vendor/bundle/ruby/2.0.0/gems/hitimes-1.2.2```

```
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /Users/alam/.rbenv/versions/2.0.0-p353/bin/ruby extconf.rb
/Users/alam/.rbenv/versions/2.0.0-p353/bin/ruby: invalid switch in RUBYOPT: -h (RuntimeError)


Gem files will remain installed in /Volumes/alam's home/fastly/fastly-jekyll/_vendor/bundle/ruby/2.0.0/gems/hitimes-1.2.2 for inspection.
Results logged to /Volumes/alam's home/fastly/fastly-jekyll/_vendor/bundle/ruby/2.0.0/gems/hitimes-1.2.2/ext/hitimes/c/gem_make.out
An error occurred while installing hitimes (1.2.2), and Bundler cannot continue.
Make sure that `gem install hitimes -v '1.2.2'` succeeds before bundling.
```

How we fixed it:

`bundle install --path /tmp/delete`

`mv /tmp/delete/* _vendor/bundle/`

`bundle install --path _vendor/bundle`

**Comment by thommahoney** [comment]
This can be reproduced using the command `gem install hitimes --path '/some path/name'

**Comment by copiousfreetime** [comment]
Thanks for the info, I'll see if I can figure out why this is happening when installing hitimes, I would assume this issue would be happening with other gems, especially other gems with extensions.

**Comment by thommahoney** [comment]
Unfortunately I don't know enough about how c extensions are configured and compiled to be of any help. I found a bug that was fixed two years ago in Ruby core that apparently solved this problem but the issue persists (obviously)

**Comment by copiousfreetime** [comment]
This looks like it was an issue with rubygems before version 2.4.2. All gems with extensions would fail if there was a space in the path. It was fixed in  rubygems/rubygems#949. 

```
% gem --version
2.4.6
% gem install hitimes --install-dir '/tmp/some path/name'Fetching: hitimes-1.2.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed hitimes-1.2.2
1 gem installed
```

So looks like you should `gem update --system` and you'll be good to go. @thommahoney @amyrlam let me know if that works for you and I'll close this ticket.

**Comment by amyrlam** [comment]
It's working for me now, sorry that we did not catch it was just a gem update issue! Appreciate it.

**Comment by thommahoney** [comment]
We should have talked to @drbrain! Thanks @copiousfreetime and sorry for wasting your time.

**Comment by copiousfreetime** [comment]
Glad to help, please let me know when you find the next :beetle:
