### ISSUE TITLE
`require': cannot load such file -- hitimes/hitimes (LoadError)

### ISSUE THREAD

**Issue by kddeisz** [copiousfreetime/hitimes#41]
bundle/gems/hitimes-1.2.2/lib/hitimes.rb:37:in `rescue in <top (required)>'

Keep getting this error when trying to run integration tests on Rails. Source seems to be under the impression that there's a hitimes/hitimes file but I can't find it anywhere.

**Comment by kddeisz** [comment]
Weird... I had to reinstall all my gems, but that fixed it.

**Comment by copiousfreetime** [comment]
to me it sounds like the installation of hitimes never happend. Hitimes uses a C extension and that will end up in the lib/hitimes/hitimes.so of the installed gem. If it isn't there then something happened during the install. I'm not sure what would have caused it, bundler would have noted if the install had failed. All I can think of is if something happened to accidentally delete the binary extension from the installed gem. Maybe a crazy rake clean or something along those lines.

I think I'll add a catch in there to explicitly call out that the extension portion doesn't appear to be installed.
