### ISSUE TITLE
error installing hitimes in ubuntu 

### ISSUE THREAD

**Issue by javadudealok** [copiousfreetime/hitimes#45]
Building native extensions.  This could take a while...
ERROR:  Error installing hitimes:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.2 -r ./siteconf20150630-27050-8zupgc.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.2.0/gems/hitimes-1.2.2 for inspection.
Results logged to /var/lib/gems/2.2.0/extensions/x86_64-linux/2.2.0/hitimes-1.2.2/gem_make.out

 sudo gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.5
  - RUBY VERSION: 2.2.2 (2015-04-13 patchlevel 95) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /var/lib/gems/2.2.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.2
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /home/alok/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/2.2.0
     - /home/alok/.gem/ruby/2.2.0
     - /usr/share/rubygems-integration/2.2.0
     - /usr/share/rubygems-integration/all
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin

**Comment by javadudealok** [comment]
alok@alok-ThinkPad-T450:~$ /usr/bin/ruby2.2 -r rbconfig -r pp -e 'pp RbConfig::CONFIG'
{"DESTDIR"=>"",
 "MAJOR"=>"2",
 "MINOR"=>"2",
 "TEENY"=>"0",
 "PATCHLEVEL"=>"95",
 "INSTALL"=>"/usr/bin/install -c",
 "EXEEXT"=>"",
 "prefix"=>"/usr",
 "ruby_install_name"=>"ruby2.2",
 "RUBY_INSTALL_NAME"=>"ruby2.2",
 "RUBY_SO_NAME"=>"ruby-2.2",
 "exec"=>"exec",
 "ruby_pc"=>"ruby-2.2.pc",
 "PACKAGE"=>"ruby",
 "BUILTIN_TRANSSRCS"=>" newline.c",
 "USE_RUBYGEMS"=>"YES",
 "MANTYPE"=>"doc",
 "NROFF"=>"/usr/bin/nroff",
 "vendorarchhdrdir"=>"/usr/include/x86_64-linux-gnu/ruby-2.2.0/vendor_ruby",
 "sitearchhdrdir"=>"/usr/include/x86_64-linux-gnu/ruby-2.2.0/site_ruby",
 "rubyarchhdrdir"=>"/usr/include/x86_64-linux-gnu/ruby-2.2.0",
 "vendorhdrdir"=>"/usr/include/ruby-2.2.0/vendor_ruby",
 "sitehdrdir"=>"/usr/include/ruby-2.2.0/site_ruby",
 "rubyhdrdir"=>"/usr/include/ruby-2.2.0",
 "RUBY_SEARCH_PATH"=>"",
 "UNIVERSAL_INTS"=>"",
 "UNIVERSAL_ARCHNAMES"=>"",
 "configure_args"=>
  " '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=${prefix}/lib/ruby2.2' '--disable-maintainer-mode' '--disable-dependency-tracking' '--enable-multiarch' '--target=x86_64-linux-gnu' '--program-suffix=2.2' '--with-soname=ruby-2.2' '--enable-shared' '--disable-rpath' '--with-baseruby=/usr/bin/ruby' '--with-sitedir=/usr/local/lib/site_ruby' '--with-sitearchdir=/usr/local/lib/x86_64-linux-gnu/site_ruby' '--enable-ipv6' '--with-dbm-type=gdbm_compat' 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'FFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4' 'GCJFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -L/build/buildd/ruby2.2-2.2.2/debian/lib' '--with-tcltkversion=8.5' '--with-tclConfig-dir=/usr/lib/x86_64-linux-gnu/tcl8.5/tclConfig.sh' '--with-tkConfig-dir=/usr/lib/x86_64-linux-gnu/tk8.5/tkConfig.sh' '--with-tcllib=tcl8.5' '--with-tklib=tk8.5' '--with-tcl-include=/usr/include/tcl8.5' '--with-tk-include=/usr/include/tcl8.5' '--with-tcl-lib=/usr/lib/x86_64-linux-gnu' '--with-tk-lib=/usr/lib/x86_64-linux-gnu' 'build_alias=x86_64-linux-gnu' 'target_alias=x86_64-linux-gnu'",
 "vendorarchdir"=>"/usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/2.2.0",
 "vendorlibdir"=>"/usr/lib/ruby/vendor_ruby/2.2.0",
 "vendordir"=>"/usr/lib/ruby/vendor_ruby",
 "sitearchdir"=>"/usr/local/lib/x86_64-linux-gnu/site_ruby",
 "sitelibdir"=>"/usr/local/lib/site_ruby/2.2.0",
 "sitedir"=>"/usr/local/lib/site_ruby",
 "rubyarchdir"=>"/usr/lib/x86_64-linux-gnu/ruby/2.2.0",
 "rubylibdir"=>"/usr/lib/ruby/2.2.0",
 "ruby_version"=>"2.2.0",
 "sitearch"=>"x86_64-linux-gnu",
 "arch"=>"x86_64-linux-gnu",
 "sitearchincludedir"=>"/usr/include/x86_64-linux-gnu",
 "archincludedir"=>"/usr/include/x86_64-linux-gnu",
 "sitearchlibdir"=>"/usr/lib/x86_64-linux-gnu",
 "archlibdir"=>"/usr/lib/x86_64-linux-gnu",
 "libdirname"=>"archlibdir",
 "RUBY_EXEC_PREFIX"=>"/usr",
 "RUBY_LIB_VERSION"=>"",
 "RUBY_LIB_VERSION_STYLE"=>"3\t/* full */",
 "RI_BASE_NAME"=>"ri",
 "ridir"=>"/usr/share/ri",
 "rubysitearchprefix"=>"/usr/lib/x86_64-linux-gnu/ruby",
 "rubyarchprefix"=>"/usr/lib/x86_64-linux-gnu/ruby",
 "MAKEFILES"=>"Makefile GNUmakefile",
 "PLATFORM_DIR"=>"",
 "THREAD_MODEL"=>"pthread",
 "SYMBOL_PREFIX"=>"",
 "EXPORT_PREFIX"=>"",
 "COMMON_HEADERS"=>"",
 "COMMON_MACROS"=>"",
 "COMMON_LIBS"=>"",
 "MAINLIBS"=>"",
 "ENABLE_SHARED"=>"yes",
 "DLDLIBS"=>" -lc",
 "SOLIBS"=>"-lpthread -lgmp -ldl -lcrypt -lm ",
 "LIBRUBYARG_SHARED"=>"-lruby-2.2",
 "LIBRUBYARG_STATIC"=>"-lruby-2.2-static",
 "LIBRUBYARG"=>"-lruby-2.2",
 "LIBRUBY"=>"libruby-2.2.so.2.2.0",
 "LIBRUBY_ALIASES"=>"libruby-2.2.so.2.2 libruby-2.2.so",
 "LIBRUBY_SO"=>"libruby-2.2.so.2.2.0",
 "LIBRUBY_A"=>"libruby-2.2-static.a",
 "RUBYW_INSTALL_NAME"=>"",
 "rubyw_install_name"=>"",
 "EXTDLDFLAGS"=>"",
 "EXTLDFLAGS"=>"",
 "strict_warnflags"=>"-std=iso9899:1999",
 "warnflags"=>
  "-Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat",
 "debugflags"=>"-ggdb3",
 "optflags"=>"-O3 -fno-fast-math",
 "cxxflags"=>
  " -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat",
 "cflags"=>
  " -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat",
 "cppflags"=>"",
 "NULLCMD"=>":",
 "DLNOBJ"=>"dln.o",
 "INSTALLDOC"=>"all",
 "CAPITARGET"=>"nodoc",
 "RDOCTARGET"=>"rdoc",
 "DTRACE_REBUILD"=>"",
 "DTRACE_OBJ"=>"probes.o",
 "DTRACE_EXT"=>"d",
 "EXECUTABLE_EXTS"=>"",
 "ARCHFILE"=>"",
 "LIBRUBY_RELATIVE"=>"no",
 "EXTOUT"=>".ext",
 "RUNRUBY_COMMAND"=>
  "$(MINIRUBY) $(srcdir)/tool/runruby.rb --extout=.ext $(RUNRUBYOPT)",
 "PREP"=>"miniruby",
 "BTESTRUBY"=>"$(MINIRUBY)",
 "CROSS_COMPILING"=>"no",
 "TEST_RUNNABLE"=>"yes",
 "rubylibprefix"=>"/usr/lib/ruby",
 "setup"=>"Setup",
 "ENCSTATIC"=>"",
 "EXTSTATIC"=>"",
 "STRIP"=>"strip -S -x",
 "TRY_LINK"=>"",
 "LIBPATHENV"=>"LD_LIBRARY_PATH",
 "RPATHFLAG"=>"",
 "LIBPATHFLAG"=>" -L%s",
 "LINK_SO"=>"",
 "ASMEXT"=>"S",
 "LIBEXT"=>"a",
 "DLEXT2"=>"",
 "DLEXT"=>"so",
 "LDSHAREDXX"=>"g++ -shared",
 "LDSHARED"=>"gcc -shared",
 "CCDLFLAGS"=>"-fPIC",
 "STATIC"=>"",
 "ARCH_FLAG"=>"",
 "DLDFLAGS"=>"",
 "ALLOCA"=>"",
 "codesign"=>"",
 "POSTLINK"=>":",
 "WERRORFLAG"=>"-Werror",
 "CHDIR"=>"cd -P",
 "RMALL"=>"rm -fr",
 "RMDIRS"=>"rmdir --ignore-fail-on-non-empty -p",
 "RMDIR"=>"rmdir --ignore-fail-on-non-empty",
 "CP"=>"cp",
 "RM"=>"rm -f",
 "PKG_CONFIG"=>"pkg-config",
 "PYTHON"=>"",
 "DOXYGEN"=>"",
 "DOT"=>"",
 "DTRACE"=>"dtrace",
 "MAKEDIRS"=>"/bin/mkdir -p",
 "MKDIR_P"=>"/bin/mkdir -p",
 "INSTALL_DATA"=>"/usr/bin/install -c -m 644",
 "INSTALL_SCRIPT"=>"/usr/bin/install -c",
 "INSTALL_PROGRAM"=>"/usr/bin/install -c",
 "SET_MAKE"=>"",
 "LN_S"=>"ln -s",
 "NM"=>"nm",
 "DLLWRAP"=>"",
 "WINDRES"=>"",
 "OBJCOPY"=>":",
 "OBJDUMP"=>"objdump",
 "ASFLAGS"=>"",
 "AS"=>"as",
 "AR"=>"ar",
 "RANLIB"=>"ranlib",
 "try_header"=>"",
 "CC_VERSION"=>"gcc -v",
 "COUTFLAG"=>"-o ",
 "OUTFLAG"=>"-o ",
 "CPPOUTFILE"=>"-o conftest.i",
 "GNU_LD"=>"yes",
 "LD"=>"ld",
 "GCC"=>"yes",
 "EGREP"=>"/bin/grep -E",
 "GREP"=>"/bin/grep",
 "CPP"=>"gcc -E",
 "CXXFLAGS"=>
  "-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security",
 "OBJEXT"=>"o",
 "CPPFLAGS"=>"-D_FORTIFY_SOURCE=2  ",
 "LDFLAGS"=>
  "-L. -Wl,-Bsymbolic-functions -Wl,-z,relro -L/build/buildd/ruby2.2-2.2.2/debian/lib -fstack-protector -rdynamic -Wl,-export-dynamic",
 "CFLAGS"=>
  "-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC",
 "CXX"=>"g++",
 "CC"=>"gcc",
 "NACL_LIB_PATH"=>"",
 "NACL_SDK_VARIANT"=>"",
 "NACL_SDK_ROOT"=>"",
 "NACL_TOOLCHAIN"=>"",
 "target_os"=>"linux-gnu",
 "target_vendor"=>"pc",
 "target_cpu"=>"x86_64",
 "target"=>"x86_64-pc-linux-gnu",
 "host_os"=>"linux-gnu",
 "host_vendor"=>"pc",
 "host_cpu"=>"x86_64",
 "host"=>"x86_64-pc-linux-gnu",
 "RUBY_VERSION_NAME"=>"ruby-2.2.0",
 "RUBYW_BASE_NAME"=>"rubyw",
 "RUBY_BASE_NAME"=>"ruby",
 "build_os"=>"linux-gnu",
 "build_vendor"=>"pc",
 "build_cpu"=>"x86_64",
 "build"=>"x86_64-pc-linux-gnu",
 "RUBY_PROGRAM_VERSION"=>"2.2.2",
 "HAVE_BASERUBY"=>"yes",
 "target_alias"=>"x86_64-linux-gnu",
 "host_alias"=>"",
 "build_alias"=>"x86_64-linux-gnu",
 "LIBS"=>"-lpthread -lgmp -ldl -lcrypt -lm ",
 "ECHO_T"=>"",
 "ECHO_N"=>"-n",
 "ECHO_C"=>"",
 "DEFS"=>"",
 "mandir"=>"/usr/share/man",
 "localedir"=>"/usr/share/locale",
 "libdir"=>"/usr/lib",
 "psdir"=>"/usr/share/doc/ruby",
 "pdfdir"=>"/usr/share/doc/ruby",
 "dvidir"=>"/usr/share/doc/ruby",
 "htmldir"=>"/usr/share/doc/ruby",
 "infodir"=>"/usr/share/info",
 "docdir"=>"/usr/share/doc/ruby",
 "oldincludedir"=>"/usr/include",
 "includedir"=>"/usr/include",
 "localstatedir"=>"/var",
 "sharedstatedir"=>"/usr/com",
 "sysconfdir"=>"/etc",
 "datadir"=>"/usr/share",
 "datarootdir"=>"/usr/share",
 "libexecdir"=>"/usr/lib/ruby2.2",
 "sbindir"=>"/usr/sbin",
 "bindir"=>"/usr/bin",
 "program_transform_name"=>"s&$&2.2&;s&^&&",
 "exec_prefix"=>"/usr",
 "PACKAGE_URL"=>"",
 "PACKAGE_BUGREPORT"=>"",
 "PACKAGE_STRING"=>"",
 "PACKAGE_VERSION"=>"",
 "PACKAGE_TARNAME"=>"",
 "PACKAGE_NAME"=>"",
 "PATH_SEPARATOR"=>":",
 "SHELL"=>"/bin/bash",
 "archdir"=>"/usr/lib/x86_64-linux-gnu/ruby/2.2.0",
 "topdir"=>"/usr/lib/x86_64-linux-gnu/ruby/2.2.0"}

**Comment by copiousfreetime** [comment]
@javadudealok no, rubygems has a separate version that ruby.

How did you install ruby2.2? If it was via `apt-get install ruby2.2` then you will also want to install `apt-get install ruby2.2-dev build-essential`

**Comment by javadudealok** [comment]
Thanks a TON ..you saved my day

**Comment by copiousfreetime** [comment]
@javadudealok glad to help. As a general rule, if you are going to be installing ruby gems you're going to need `ruby*-dev` and `build-essential` as the installation of ruby gems with native extensions on Debian / Ubuntu requires the C language headers for ruby (`ruby*-dev`), and also a compiler/linker/make system (`build-essential`).

**Comment by pasupulaphani** [comment]
Still happens on Ubuntu 14.04 - ruby 2.2.3
```
/home/phani/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /home/phani/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
        from /home/phani/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
        from /home/phani/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:735:in `try_func'
        from /home/phani/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:966:in `block in have_library'
        from /home/phani/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
        from /home/phani/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /home/phani/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from /home/phani/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
        from /home/phani/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from /home/phani/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
        from /home/phani/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
        from /home/phani/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:961:in `have_library'
        from extconf.rb:10:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/phani/.rvm/gems/ruby-2.2.3/gems/hitimes-1.2.3 for inspection.
```

**Comment by pmontrasio** [comment]
I just run into this on Ubuntu 14.04.3. The fix was

    sudo apt-get install libgmp-dev

**Comment by copiousfreetime** [comment]
Also see #48. The `libgmp-dev` dependency has to do with the binary ruby that rvm installs.
