### ISSUE TITLE
hitimes 1.2.3 gem fails to install as a Vagrant plugin

### ISSUE THREAD

**Issue by drcraig** [copiousfreetime/hitimes#46]
I don't know if this should be a bug for your project or the vagrant-triggers Vagrant plugin, but I'll start here. Hitimes is apparently a dependency of the vagrant-triggers plugin, and version 1.2.3 now fails to install, either when installing vagrant-triggers, or when installed standalone as a vagrant plugin.
```
vagrant plugin install vagrant-triggers
vagrant plugin install hitimes --plugin-version 1.2.3
```

The error output is not terribly helpful, other than saying
```
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.
```

All of this is on Ubuntu 12.04 and Vagrant 1.7.2. I have ruby1.8-dev and build-essential installed. As a workaround for now, I'm manually installing 1.2.2 as a Vagrant plugin before installing vagrant-triggers. This works fine, but just adds more time to the install because Vagrant plugin installs (maybe all Gem installs?) seem to take a crazy long time.

**Comment by copiousfreetime** [comment]
@drcraig My initial thought is that it is because you are using ruby1.8 which was end of life'd in June of 2013. Hitimes 1.2.3 requires at least ruby 1.9.3, and 1.9.3 was end of life'd in Feb 2015.

The other option could be vagrant 1.7.2. The current version is 1.7.4. 

The weird part is, I'm looking at vagrant-triggers and there is no dependency on hitimes. Can you do a `vagrant plugin install --verbose vagrant-triggers` and post the output here? This is my output:

```
% vagrant plugin install --verbose vagrant-triggers
Installing the 'vagrant-triggers' plugin. This can take a few minutes...
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
Fetching source index from http://gems.hashicorp.com/
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/......
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using builder 3.2.2
Using bundler 1.10.5
Using ffi 1.9.10
Using childprocess 0.5.6
Using erubis 2.7.0
Using gssapi 1.2.0
Using gyoku 1.3.1
Using hashicorp-checkpoint 0.1.4
Using httpclient 2.6.0.1
Using i18n 0.7.0
Using rb-fsevent 0.9.5
Using rb-inotify 0.9.5
Using listen 3.0.2
Using little-plugger 1.1.4
Using log4r 1.1.10
Using multi_json 1.11.2
Using logging 1.8.2
Using mime-types 1.25.1
Using mini_portile 0.6.0
Using net-ssh 2.9.2
Using net-scp 1.1.2
Using net-sftp 2.1.2
Using nokogiri 1.6.3.1
Using nori 2.6.0
Using rb-kqueue 0.2.4
Using rest-client 1.6.9
Using rubyntlm 0.4.0
Using rubyzip 1.1.7
Using uuidtools 2.1.5
Using wdm 0.1.1
Using winrm 1.3.3
Using winrm-fs 0.2.0
Using vagrant 1.7.4
Using vagrant-share 1.1.4
Installing vagrant-triggers 0.5.2
Installed the plugin 'vagrant-triggers (0.5.2)'!
```

**Comment by copiousfreetime** [comment]
@drcraig I just built out a fresh precise64 box, build-essential and installed vagrant 1.7.2 from .deb. 
When I did `vagrant plugin install --verbose vagrant-triggers` it installed hitimes 1.2.2. 

I wiped vagrant and then installed vagrant 1.7.4 from .deb and did `vagrant plugin install --verbose vagrant-triggers` and hitimes was not installed.

Unfortunately I'm unable to replicate what you have happening. My suggestion is to update vagrant, and then probably remove your `.vagrant.d` directory and reinstall your plugins

**Comment by copiousfreetime** [comment]
@drcraig I'm going to close this issue for now as I think the proper solution is update vagrant to 1.7.4. Please let me know if there is some other approach you have taken. Thanks for your report.

**Comment by drcraig** [comment]
@copiousfreetime thanks for taking the time to investigate. We were eventually able to upgrade to 1.7.4 (and now 1.8.1, which is even better), and it fixed the issue just as you said.

**Comment by copiousfreetime** [comment]
@drcraig Good to know, thanks for the feedback.
