### ISSUE TITLE
WARN: Unresolved specs during Gem::Specification.reset

### ISSUE THREAD

**Issue by oswaldoferreira** [copiousfreetime/hitimes#49]
Warning while running specs using rspec 3.3.3 (hitimes 1.2.3).

- `ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]`

```
WARN: Unresolved specs during Gem::Specification.reset:
      hitimes (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
```

Obs: Hitimes is a sidekiq 3.5.0 dependency on my project.

**Comment by copiousfreetime** [comment]
Interesting, considering hitimes doesn't use rspec :smile:. The specs in hitimes are the spec format of minitest.

According to http://stackoverflow.com/questions/17936340/unresolved-specs-during-gemspecification-reset it may be that you have more than one verision of hitimes installed and that is what is causing this to show up. 

Maybe that will do it?

**Comment by oswaldoferreira** [comment]
A simple cleanup stopped it :+1:. Closing here.
