### ISSUE TITLE
Cannot compile version 1.2.3 on El Capitan

### ISSUE THREAD

**Issue by mochnatiy** [copiousfreetime/hitimes#51]
Hello!
I have had a several attempts to install hitimes (1.2.3) on El Capitan and all of these were failed with the same error:

```
gem install hitimes -v '1.2.3'
Building native extensions.  This could take a while...
ERROR:  Error installing hitimes:
	ERROR: Failed to build gem native extension.

    /Users/sergey/.rbenv/versions/2.2.1/bin/ruby -r ./siteconf20151013-22358-1s627qe.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling hitimes.c
compiling hitimes_instant_clock_gettime.c
compiling hitimes_instant_osx.c
compiling hitimes_instant_windows.c
compiling hitimes_interval.c
compiling hitimes_stats.c
linking shared-object hitimes/2.2/hitimes.bundle
ld: library not found for -lgmp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [hitimes.bundle] Error 1

make failed, exit code 2
```
I have:
- ruby 2.2.1 from rbenv:
```
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
```
- gmp 6.0.0a from brew
- gcc:

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```
May be I do something wrong, but I will ask here.
Thank's.

**Comment by copiousfreetime** [comment]
@mochnatiy How did you install ruby? I think if ruby was installed from source you should be fine. Hitimes itself has no dependency on libgmp, the `-lgmp` flag comes from how ruby was built itself. You should see it if you do `ruby -rrbconfig -e 'puts RbConfig::CONFIG.find_all { |k,v| puts "#{k} : #{v}" if v =~ /gmp/ }'`

This is the same error that folks in #48 were getting.

**Comment by mochnatiy** [comment]
Thank's!
I installed ruby from rbenv.
The interesting point is my next steps:

1) Update ruby-build from homebrew
2) Uninstall ruby 2.2.1 from rbenv
3) Install ruby 2.2.1 from rbenv

And all works ok, I'm using hitimes now in my project. May be it was issue from Yosemite -> El Capitan upgrade process. Don't know.

**Comment by copiousfreetime** [comment]
@mochnatiy I would agree with the Yosemite -> El Capitan process. Basically anything that you compiled on your own machine on Yosemite will need to be rebuilt for El Capitan. So, if you haven't I would reinstall everything from homebrew and rebuild all rubies in rbenv.

**Comment by neurogenesis** [comment]
@mochnatiy , you probably already figured this out... but if you've upgraded to El Capitan, you'll have to ensure you have all the xcode tools installed and the licenses accepted:

```xcode-select --install```
