### ISSUE TITLE
Cannot install on Linux with glibc 2.19

### ISSUE THREAD

**Issue by alexandermayr** [copiousfreetime/hitimes#52]
I'm not sure but that might be a compatibility issue since glibc 2.17 moved clock_* functions into the main lib. see https://sourceware.org/ml/libc-announce/2012/msg00001.html

Building native extensions.  This could take a while...
ERROR:  Error installing hitimes:
	ERROR: Failed to build gem native extension.

    /home/ef/.rvm/rubies/ruby-2.2.3/bin/ruby -r ./siteconf20151027-2357-17citwz.rb extconf.rb
checking for clock_gettime() in -lrt... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/ef/.rvm/rubies/ruby-2.2.3/bin/$(RUBY_BASE_NAME)
	--with-rtlib
	--without-rtlib
/home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:735:in `try_func'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:966:in `block in have_library'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:961:in `have_library'
	from extconf.rb:10:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/ef/.rvm/gems/ruby-2.2.3/gems/hitimes-1.2.3 for inspection.
Results logged to /home/ef/.rvm/gems/ruby-2.2.3/extensions/x86_64-linux/2.2.0/hitimes-1.2.3/gem_make.out

**Comment by copiousfreetime** [comment]
Thanks for the report. Can you post the contents of ` /home/ef/.rvm/gems/ruby-2.2.3/extensions/x86_64-linux/2.2.0/hitimes-1.2.3/gem_make.out` please?

**Comment by alexandermayr** [comment]
hi jeremy,

it's just as in stdout:


/home/ef/.rvm/rubies/ruby-2.2.3/bin/ruby -r ./siteconf20151027-2357-17citwz.rb extconf.rb
checking for clock_gettime() in -lrt... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/ef/.rvm/rubies/ruby-2.2.3/bin/$(RUBY_BASE_NAME)
	--with-rtlib
	--without-rtlib
/home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:735:in `try_func'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:966:in `block in have_library'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
	from /home/ef/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:961:in `have_library'
	from extconf.rb:10:in `<main>'

**Comment by copiousfreetime** [comment]
The error message `The compiler failed to generate an executable file. You have to install development tools` is the result of a pre-test to make sure that the compiler and linker all work/exist before testing the existence of the `-lrt`. 

If you are on a debian/ubuntu box you'll want to make sure you do `sudo apt-get install build-essential libgmp-devel`, which will be necessary for any ruby with a C extension.

**Comment by alexandermayr** [comment]
I'm not sure how libgmp-dev was connected with the libc issue but it's fixed it. thanks for your help!
