### ISSUE TITLE
gem install hitimes not working

### ISSUE THREAD

**Issue by kosto1992** [copiousfreetime/hitimes#53]
Hello,
I have problem with hitimes in Widnows 8.1 using gem.

Error:
C:\Ruby22-x64\DevKit>gem install hitimes -v '1.2.2'
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing hitimes:
        ERROR: Failed to build gem native extension.

    C:/Ruby22-x64/bin/ruby.exe -r ./siteconf20151029-4056-13cg0r2.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="

make failed, uncaught signal 11

Gem files will remain installed in C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/hitimes-1.2.2 for inspection.
Results logged to C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/hitimes-1.2.2/gem_make.out

RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.8
  - RUBY VERSION: 2.2.3 (2015-08-18 patchlevel 173) [x64-mingw32]
  - INSTALLATION DIRECTORY: C:/Ruby22-x64/lib/ruby/gems/2.2.0

Any idea how to fix it?

**Comment by copiousfreetime** [comment]
Hi @kosto1992 please use the most recent version of hitimes. just do `gem install hitimes`

**Comment by kosto1992** [comment]
Thanks for fast reply, but it is not working either. I still get same error.

C:\Ruby22-x64\DevKit>gem install hitimes
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing hitimes:
        ERROR: Failed to build gem native extension.

    C:/Ruby22-x64/bin/ruby.exe -r ./siteconf20151029-9148-l1k5v3.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="

make failed, uncaught signal 11

Gem files will remain installed in C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/hitimes-1.2.3 for inspection.
Results logged to C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/hitimes-1.2.3/gem_make.out

**Comment by copiousfreetime** [comment]
@kosto1992 My apologies, apparently I never saw this and followed up. You shouldn't need devkit for hitimes, I build a fat binary that will work for windows, so you should just be able to install the version for windows and the gem command should download and install that one. 

if you are still having this issue, reopen this ticket and post the output of `gem env`.

Again my apologies.
