### ISSUE TITLE
Native extension load issue with Ruby 2.1.10

### ISSUE THREAD

**Issue by wpiekutowski** [copiousfreetime/hitimes#55]
This gem requires a native extension to function. In case of Ruby 2.1.x, this extension is supposed to be stored in `path_to_gems/hitimes-1.2.3/lib/hitimes/2.1/hitimes.bundle`. This works correctly on Ruby 2.1.0-2.1.9. However, in case of Ruby 2.1.10, extension is stored in `path_to_gems/hitimes-1.2.3/lib/hitimes/2.1.10/hitimes.bundle`. A dot and Ruby patch version aren't stripped properly. This isn't exactly where it should be, but that works.

When using rbenv, capistrano, bundle and a version of hitimes installed earlier with Ruby older than 2.1.10, native extension will end up in `path_to_gems/hitimes-1.2.3/lib/hitimes/2.1/hitimes.bundle`, but the gem will look for it in `path_to_gems/hitimes-1.2.3/lib/hitimes/2.1.10/hitimes.bundle`. In that case, native extension can't be found and there's an error:
```
/app_path/shared/bundle/ruby/2.1.0/gems/hitimes-1.2.3/lib/hitimes.rb:46:in `<top (required)>': Unable to find binary extension, was hitimes installed correctly? (LoadError)
```

**Env details**

Ruby
```
$ ruby -e 'puts RUBY_DESCRIPTION'
ruby 2.1.10p492 (2016-04-01 revision 54464) [x86_64-darwin15.0]
```

Operating system
OS X 10.11.4

hitimes version
1.2.3 (master)

**Comment by copiousfreetime** [comment]
@wpiekutowski merged your code in, doing a release tomorrow

**Comment by copiousfreetime** [comment]
@wpiekutowski new version pushed

**Comment by wpiekutowski** [comment]
Thank you.
