### ISSUE TITLE
Hello, i'm having troubles running opengl in ruby

### ISSUE THREAD

**Issue by robertoxyz20** [copiousfreetime/hitimes#58]
ERROR [
C:\Ruby23>C:\Ruby23\rub.rb
C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- opengl/opengl (LoadError)
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/opengl-0.9.2-x86-mingw32/lib/opengl.rb:31:in `rescue in <top (required)>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/opengl-0.9.2-x86-mingw32/lib/opengl.rb:27:in`<top (required)>'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in`rescue in require'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from C:/Ruby23/rub.rb:1:in`<main>'
]
C:\Ruby23>gem env
RubyGems Environment:
- RUBYGEMS VERSION: 2.5.1
- RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [i386-mingw32]
- INSTALLATION DIRECTORY: C:/Ruby23/lib/ruby/gems/2.3.0
- USER INSTALLATION DIRECTORY: C:/Users/roberto/.gem/ruby/2.3.0
- RUBY EXECUTABLE: C:/Ruby23/bin/ruby.exe
- EXECUTABLE DIRECTORY: C:/Ruby23/bin
- SPEC CACHE DIRECTORY: C:/Users/roberto/.gem/specs
- SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
- RUBYGEMS PLATFORMS:
  - ruby
  - x86-mingw32
- GEM PATHS:
  - C:/Ruby23/lib/ruby/gems/2.3.0
  - C:/Users/roberto/.gem/ruby/2.3.0
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - https://rubygems.org/
- SHELL PATH:
  - C:\Ruby23\bin
  - C:\Ruby23\bin
  - C:\Windows\system32
  - C:\Windows
  - C:\Windows\System32\Wbem
  - C:\Windows\System32\WindowsPowerShell\v1.0\
  - C:\Program Files\Skype\Phone\
  - C:\Program Files\Shoes

C:\Ruby23>gem list

**\* LOCAL GEMS ***

ashton (0.1.6)
atk (3.0.9 x86-mingw32)
backports (3.6.8)
bigdecimal (1.2.8)
bundler (1.12.5)
cairo (1.15.2 x86-mingw32)
cairo-gobject (3.0.9 x86-mingw32)
chingu (0.8.1)
chipmunk (6.1.3.4)
conject (0.1.8)
crack (0.4.3)
did_you_mean (1.0.0)
domain_name (0.5.20160615)
ffi (1.9.14 x86-mingw32)
fxruby (1.6.34 x86-mingw32)
gamebox (0.5.5)
gdk3 (3.0.9 x86-mingw32)
gdk_pixbuf2 (3.0.9 x86-mingw32)
gio2 (3.0.9 x86-mingw32)
git (1.3.0)
glib2 (3.0.9 x86-mingw32)
gobject-introspection (3.0.9 x86-mingw32)
gosu (0.10.8 x86-mingw32)
gtk (0.1.0)
gtk2 (3.0.9 x86-mingw32)
gtk3 (3.0.9 x86-mingw32)
gtksourceview3 (3.0.9 x86-mingw32)
http-cookie (1.0.2)
httpclient (2.8.2.2)
i18n (0.7.0)
io-console (0.4.5)
json (2.0.2, 1.8.3)
kvo (0.1.0)
listen (3.1.5)
mime-types (3.1)
mime-types-data (3.2016.0521)
mini_portile (0.6.2)
minitest (5.8.3)
net-telnet (0.1.1)
netrc (0.11.0)
opengl (0.9.2 x86-mingw32)
pango (3.0.9 x86-mingw32)
pkg-config (1.1.7)
power_assert (0.2.6)
psych (2.0.17)
publisher (1.1.2)
rake (10.4.2)
rb-fsevent (0.9.7)
rb-inotify (0.9.7)
rdoc (4.2.1)
require_all (1.3.3)
rest-client (2.0.0 x86-mingw32)
rsvg2 (3.0.9 x86-mingw32)
ruby_dep (1.4.0)
safe_yaml (1.0.4)
specific_install (0.3.2)
test-unit (3.1.5)
texplay (0.4.3 x86-mingw32)
thor (0.19.1)
tween (0.1.2)
unf (0.1.4)
unf_ext (0.0.7.2 x86-mingw32)
## visualruby (3.0.22)

Can you help me?

**Comment by copiousfreetime** [comment]
Unfortunately, this I don't think has anything to do with the hitimes gem. I don't think I can help.
