### ISSUE TITLE
Make error on windows 

### ISSUE THREAD

**Issue by Startouf** [copiousfreetime/hitimes#59]
I a trying to install the gem on my windows 10, I am running into the following error

```
PS:3 > gem install hitimes
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
C:\Dev\Ruby22-x64\Devkit\bin\make.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0
ERROR:  Error installing hitimes:
        ERROR: Failed to build gem native extension.

    C:/Dev/Ruby22-x64/bin/ruby.exe -r ./siteconf20160915-736-1dl5tc9.rb extconf.rb
creating Makefile

make "DESTDIR=" clean
      0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
AllocationBase 0xBB0000, BaseAddress 0xCC0000, RegionSize 0xED000, State 0x2000
C:\Dev\Ruby22-x64\Devkit\bin\make.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0

make "DESTDIR="
      0 [main] echo 8500 open_stackdumpfile: Dumping stack trace to echo.exe.stackdump
make: *** [hitimes-x64-mingw32.def] Error 5

make failed, exit code 2

Gem files will remain installed in C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/hitimes-1.2.4 for inspection.
Results logged to C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/hitimes-1.2.4/gem_make.out

[C:\Dev\]
PS:4 > ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x64-mingw32]
```

I had no troubles installing gems that required native tools before (eg. Nokogiri). I'm trying to install hitimes `1.2.4`

**Comment by copiousfreetime** [comment]
On windows you should not have to build the gem, I package fat binaries for hitimes, so you should be installing the binary version of the gem, in particular https://rubygems.org/gems/hitimes/versions/1.2.4-x86-mingw32

If you would can you run `gem env` and drop the output here? I see if I can figure out why you didn't install the fat binary version of the gem.

**Comment by wjlroe** [comment]
Looks like the reporter's Ruby is x64-mingw32 (as is mine) and the fat binary is x86-mingw32. Installing a 32bit ruby resolves this.

**Comment by copiousfreetime** [comment]
Closing as there has been no traffic from the original reporter.

**Comment by predatorian3** [comment]
Well, this is a bummer. I have a co-worker who's having the same issues. We're trying to install berkshelf which depends on this gem, and getting the same errors as above. We included the devkitvars.bat, and it built the JSON gem and a few others, but not hitimes. 

He's running 
* Windows 10
* Ruby 2.4.1p111
* DevKit for Ruby 2+ 64bit

**Comment by copiousfreetime** [comment]
@predatorian3 can you attach the errors you are getting. If you are using DevKit then you should be able to build hitimes from the source gem not the fatbinary gem. I'd like to make sure hitimes works for everyone.

**Comment by predatorian3** [comment]
Here is the error. He closed the terminal prior to this, so I don't have the original output with the proof that it built other gems.

```
C:\Users\user01\Documents\ets_tools_aws-repo\ets_tools_aws-repo (master)
λ C:\Ruby\DevKit\devkitvars.bat
Adding the DevKit to PATH...

C:\Users\user01\Documents\ets_tools_aws-repo\ets_tools_aws-repo (master)
λ bundle install
The latest bundler is 1.16.0.pre.2, but you are currently running 1.15.4.
To update, run `gem install bundler --pre`
Failed to load C:/Users/user01/.gemrc, (<unknown>): did not find expected key while parsing a block mapping at line 2 column 1
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 12.0.0
Using public_suffix 2.0.5
Using jmespath 1.3.1
Using multipart-post 2.0.0
Using httpclient 2.8.3
Using buff-extensions 2.0.0
Using hashie 3.5.5
Using buff-ignore 1.2.0
Using buff-ruby_engine 1.0.0
Fetching hitimes 1.2.4
Installing hitimes 1.2.4 with native extensions
Fetching nio4r 2.0.0
Installing nio4r 2.0.0 with native extensions
Using fuzzyurl 0.9.0
Using mixlib-config 2.2.4
Using ffi 1.9.18 (x64-mingw32)
Using wmi-lite 1.0.0
Using erubis 2.7.0
Fetching json 2.0.4
Installing json 2.0.4 with native extensions
Using mixlib-log 1.7.1
Using retryable 2.0.4
Using semverse 2.0.0
Using cleanroom 1.0.0
Using minitar 0.6.1
Using molinillo 0.5.7
Using thor 0.19.1
Using bundler 1.15.4
Using fork 1.0.1
Using git 1.3.0
Using addressable 2.5.1
Using aws-sdk-core 2.6.1
Using faraday 0.9.2
Using varia_model 0.6.0
Using buff-shell_out 1.1.0
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/hitimes-1.2.4/ext/hitimes/c
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20170914-15616-1i33gto.rb extconf.rb
creating Makefile

current directory:
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/hitimes-1.2.4/ext/hitimes/c
make "DESTDIR=" clean

current directory:
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/hitimes-1.2.4/ext/hitimes/c
make "DESTDIR="
generating hitimes-x64-mingw32.def
compiling hitimes.c
compiling hitimes_instant_clock_gettime.c
compiling hitimes_instant_osx.c
compiling hitimes_instant_windows.c
compiling hitimes_interval.c
compiling hitimes_stats.c
linking shared-object hitimes/2.4/hitimes.so
c:/ruby/devkit/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.7.2/../../../../x86_64-w64-mingw32/bin/ld.exe:
cannot find -lgmp
collect2.exe: error: ld returned 1 exit status
make: *** [hitimes.so] Error 1

make failed, exit code 2

Gem files will remain installed in
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/hitimes-1.2.4 for inspection.
Results logged to
C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/hitimes-1.2.4/gem_make.out

An error occurred while installing hitimes (1.2.4), and Bundler cannot
continue.
Make sure that `gem install hitimes -v '1.2.4'` succeeds before bundling.

In Gemfile:
  berkshelf was resolved to 5.6.4, which depends on
    berkshelf-api-client was resolved to 3.0.0, which depends on
      ridley was resolved to 5.1.0, which depends on
        celluloid-io was resolved to 0.16.2, which depends on
          celluloid was resolved to 0.16.0, which depends on
            timers was resolved to 4.0.4, which depends on
              hitimes
```

**Comment by copiousfreetime** [comment]
That is weird, that's not actually an error with hitimes. It has to do with the linker flags that the ruby that is building hitimes has set in the config.

I would really like to see the output from the json build, because it should have this same error. the linking against  `libgmp` error is because of the linker flags that are in part of the rbconfig.

There should be a `gem_make.out` somewhere for each of the native extensions that are installed. Probably in `$GEM_HOME/extensions/..../gem_make.out`

**Comment by predatorian3** [comment]
```
c:\Ruby24-x64\lib\ruby\gems\2.4.0\extensions\x64-mingw32\2.4.0\json-2.0.4
λ cat gem_make.out
current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.0.4/ext/json/ext/generator
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20170914-15616-qsbjow.rb extconf.rb
creating Makefile

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.0.4/ext/json/ext/generator
make "DESTDIR=" clean

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.0.4/ext/json/ext/generator
make "DESTDIR="
generating generator-x64-mingw32.def
compiling generator.c
linking shared-object json/ext/generator.so
c:/ruby/devkit/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.7.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgmp
collect2.exe: error: ld returned 1 exit status
make: *** [generator.so] Error 1

make failed, exit code 2
```

**Comment by predatorian3** [comment]
I thought it built correctly, because we didn't get an error building this time with MinGW on WIndows after including the devkitvars.bat

**Comment by copiousfreetime** [comment]
So there are 2 ways to fix this
* one is to make sure that the ruby you are using is not built against `libgmp`
* or if the ruby is built against `libgmp` then make sure that the headers/shared library of `libgmp` are available so that the `ld` or `collect` command works.

**Comment by predatorian3** [comment]
If its https://rubyinstaller.org/ , I'm not sure if its built against libgmp. I'm going to assume it is. Never really built Ruby on Windows before, always used the packaged version or one that came with Cygwin, or MSYS2.

**Comment by predatorian3** [comment]
We're working on getting MSYS2 installed and configured to try building Ruby, or using that as our build system.

**Comment by copiousfreetime** [comment]
@predatorian3 sounds good, let me know what problems you have with hitimes and I'll do what I can to help out.

**Comment by predatorian3** [comment]
So, ended up downgrading from RubyInstaller version 2.4.1 for Windows to 2.3.1 and this Gem seemed to have worked as we were able to install the gem. Now we're having to fix the OpenSSL issue that comes with windows as well. Thank you for being super attentative to this issue @copiousfreetime 

I'm not sure what the actual issue is for that then.

**Comment by copiousfreetime** [comment]
Glad to help! I don't know off the top of my head either. I'm going to close this for now, and should you have any issues do let me know. 

Happy Programming!
