### ISSUE TITLE
wrong hitimes.gemspec version

### ISSUE THREAD

**Issue by anthraxx** [copiousfreetime/hitimes#61]
The current file contains 1.2.4 while the actual version is 1.2.5. This produces a wrong gem when building from gemspec

**Comment by copiousfreetime** [comment]
Thanks @anthraxx pushing a 1.2.6 here shortly to resolve.

**Comment by copiousfreetime** [comment]
Version 1.2.6 released a0f509047e8d0df1e6fa7c75951d067a6be5dc5f

**Comment by anthraxx** [comment]
Thanks a lot, have a great weekend
