### ISSUE TITLE
Ruby 2.5??

### ISSUE THREAD

**Issue by 98-f355-f1** [copiousfreetime/hitimes#67]
Hi
Are there plans to update this gem to Ruby 2.5?
I am trying to use the socketry gems and it seems that this gem is incompatible at the moment.
Thanks

**Comment by copiousfreetime** [comment]
@98-f355-f1 I was just assuming hitimes was 2.5 compatible. I'll check and push and update if it isn't. Do you have a particular bug that you see?

**Comment by copiousfreetime** [comment]
@98-f355-f1 I just tested on travis-ci hitimes works out of the box on ruby 2.5. If you have any futher details on the issue you are seeing, please let me know.
