### ISSUE TITLE
Installation on ubuntu 18.04 with ruby 2.5

### ISSUE THREAD

**Issue by trocolit2** [copiousfreetime/hitimes#68]
Hi,
I installed a fresh new UBUNTU 18.04, and I am facing errors during hitimes installation.
After ran the `gem install hitimes` command I got the error shown in follow
```
$ sudo gem install timers
Building native extensions. This could take a while...
ERROR:  Error installing timers:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/hitimes-1.3.0/ext/hitimes/c
/usr/bin/ruby2.5 -r ./siteconf20180620-14797-1trreao.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.5.0/gems/hitimes-1.3.0 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/hitimes-1.3.0/gem_make.out
```
For Ubuntu 18.04, the ruby version is 2.5.
Could any one gives me tips to solve this issue?
I can provide more detailed information if needed.

Thanks in advance.

**Comment by copiousfreetime** [comment]
@trocolit2 looks like you are missing the ruby header files - which is part of `ruby-ev` You probably need to run:

`apt install ruby-dev libffi-dev build-essential`

**Comment by trocolit2** [comment]
Hi @copiousfreetime 
Thanks for your quickly answer, I really appreciated.  
I did not installed these two packages, 'ruby-dev libffi-dev'.
The last Ubuntu LTS, the ruby installation used to include the ruby-dev.
Again thanks for your time!

**Comment by copiousfreetime** [comment]
@trocolit2 Glad to help. let me know if you have any other issues.
