### ISSUE TITLE
How to solve this error !! nio4r not installed !!

### ISSUE THREAD

**Issue by sidhant387474** [copiousfreetime/hitimes#80]
![Screenshot_2023-04-04-19-54-18-04_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/129873197/229824758-643c478e-5455-4680-b016-5a4dabe0f322.jpg)

**Comment by copiousfreetime** [comment]
Wrong project - take this up with metasploit / nio4r

**Comment by copiousfreetime** [comment]
I'm not sure how you ended up deciding the issue you are having is hitimes related, based upon your screenshot, it is definitely not.

I would go back to whomever or wherever you received the commands that you executed and ask them for support in resolving your issue.
